=== chandras10/pglite/pg_policy.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
<!--
    PeregrineGuard Policy DTD
-->

<!ENTITY % BOOLEAN "(False|True|true|false)">
<!ENTITY % STRING "CDATA">
<!ENTITY % NUMBER "CDATA">

<!ENTITY % ACTION "(allow|reject|deny)">
<!ENTITY % IPADDRESS "CDATA">
<!ENTITY % NETMASK "CDATA">

<!ELEMENT FWObject EMPTY>
<!ATTLIST FWObject 
          id ID #REQUIRED   
          type (IPv4|IPv4List|IPv4Subnet|MACAddress|MACList|ObjectRef|Policy|PolicyRule|DeviceClass|DeviceType|OSName|OSVersion|UserName|UserRole|Location|Port|PortRange|PortList|Any) #REQUIRED
          value CDATA #REQUIRED>

<!-- Reference to Objects child -->
<!ELEMENT ObjectRef EMPTY>
<!ATTLIST ObjectRef ref IDREF #REQUIRED>

<!ELEMENT Src (ObjectRef)+>
<!ATTLIST Src neg (False|True|true|false) #REQUIRED>

<!ELEMENT Dst (ObjectRef)+>
<!ATTLIST Dst neg (False|True|true|false) #REQUIRED>

<!ELEMENT PolicyRule ((Src),(Dst))>
<!ATTLIST PolicyRule 
	id ID #REQUIRED 
        position CDATA #REQUIRED
	action  (allow|reject|deny) #REQUIRED
	log (False|True|true|false) #REQUIRED>

<!ELEMENT Policy ((PolicyRule)+)>

<!ELEMENT FWPolicy ((FWObject)+,Policy)>

=== chandras10/pglite/test.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE FWPolicy SYSTEM "/usr/local/etc/pgguard/pg_policy.dtd">
<FWPolicy>
 <FWObject id="fwobject_1" type="OSName" value="iOS"/>
 <FWObject id="fwobject_2" type="PortRange" value="10-40"/>
 <FWObject id="fwobject_3" type="PortList" value="10, 20, 30, 40"/>
 <FWObject id="fwobject_4" type="IPv4List" value="192.168.10.210 or 192.168.10.211 or 192.168.10.212 or 192.168.10.213"/>
 <FWObject id="fwobject_5" type="Port" value="20"/>
 <FWObject id="fwobject_6" type="IPv4Subnet" value="192.168.0.0/16"/>
 <FWObject id="fwobject_7" type="IPv4" value="192.168.10.218"/>
 <Policy>
  <PolicyRule position="0" id="Rule1" log="False" action="reject">
   <Src neg="False">
    <ObjectRef ref="fwobject_1"/>
   </Src>
   <Dst neg="False">
    <ObjectRef ref="fwobject_3"/>
    <ObjectRef ref="fwobject_4"/>
    <ObjectRef ref="fwobject_5"/>
    <ObjectRef ref="fwobject_6"/>
    <ObjectRef ref="fwobject_7"/>
    <ObjectRef ref="fwobject_2"/>
   </Dst>
  </PolicyRule>
 </Policy>
</FWPolicy>
